### ISSUE TITLE
Android app crashes after install

### ISSUE THREAD

**Issue by rishchou** [EliotAndres/tensorflow-2-run-on-mobile-devices-ios-android-browser#4]
I am getting the following error when installing Android app:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: me.ndres.tflitedemo, PID: 6314
    java.lang.RuntimeException: Unable to start activity ComponentInfo{me.ndres.tflitedemo/me.ndres.tflitedemo.CameraActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void me.ndres.tflitedemo.OverlayView.addCallback(me.ndres.tflitedemo.OverlayView$DrawCallback)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3092)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3235)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6986)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void me.ndres.tflitedemo.OverlayView.addCallback(me.ndres.tflitedemo.OverlayView$DrawCallback)' on a null object reference
        at me.ndres.tflitedemo.Camera2BasicFragment.onViewCreated(Camera2BasicFragment.java:488)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1308)
        at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2430)
        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2209)
        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2165)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2066)
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3055)
        at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3002)
        at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:183)
        at android.app.Activity.performCreate(Activity.java:7333)
        at android.app.Activity.performCreate(Activity.java:7317)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3072)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3235) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:6986) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

**Comment by Hina55** [comment]
@EliotAndres, I got the same issue. How to resolve it?

**Comment by Hina55** [comment]
@rishchou, Did you resolve it?
